name: Deploy MusicSharing API to Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/deploy_key

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SERVER_IP }} > ~/.ssh/temp_known_hosts
        cat ~/.ssh/temp_known_hosts >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "echo Connection successful"

    - name: Deploy to server
      env:
        CONNECTION_STRING: ${{ secrets.PROD_CONNECTION_STRING }}
        JWT_KEY: ${{ secrets.PROD_JWT_KEY }}
        SENDGRID_API_KEY: ${{ secrets.PROD_SENDGRID_API_KEY }}
        SENDGRID_FROM: ${{ secrets.PROD_SENDGRID_FROM }}
        SENDGRID_ENABLESSL: ${{ secrets.PROD_SENDGRID_ENABLESSL }}
        SENDGRID_PORT: ${{ secrets.PROD_SENDGRID_PORT }}
      run: |
        echo "Deploying to server..."
        # Free port locally on remote (optional safety)
        for port in 5000; do
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "pid=\$(lsof -t -i:$port || true); if [ ! -z \"\$pid\" ]; then kill -9 \$pid || true; fi"
        done
        # Run remote deploy with environment variables
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          cd /mnt/user/appdata/musicsharing-api &&
          git fetch --quiet &&
          git reset --hard origin/master &&
          chmod +x ./deploy.sh &&
          CONNECTION_STRING='${{ secrets.PROD_CONNECTION_STRING }}' \
          JWT_KEY='${{ secrets.PROD_JWT_KEY }}' \
          EMAIL__Smtp__Host='smtp.sendgrid.net' \
          EMAIL__Smtp__Port='${{ secrets.PROD_SENDGRID_PORT }}' \
          EMAIL__Smtp__From='${{ secrets.PROD_SENDGRID_FROM }}' \
          EMAIL__Smtp__User='apikey' \
          EMAIL__Smtp__Pass='${{ secrets.PROD_SENDGRID_API_KEY }}' \
          EMAIL__Smtp__EnableSsl='${{ secrets.PROD_SENDGRID_ENABLESSL }}' \
          ./deploy.sh
        "

    - name: Notify Discord (success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"✅ API deployment succeeded!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"❌ API deployment failed.\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}